### ISSUE TITLE
Order of Plugins execution when listed with plugin seek-oss/aws-sm#v2.2.1

### ISSUE THREAD

**Issue by Sachin155** [cultureamp/aws-assume-role-buildkite-plugin#23]
I have configured the steps where plugins listed in order 

```
  - cultureamp/aws-assume-role#v0.1.0:
      role: "arn:aws:iam::1111111111111:role/buildkite-roles"
  - seek-oss/aws-sm#v2.2.1:
      env:
        GITHUB_TOKEN:
          secret-id: "buildkite-secret"
          json-key: ".github_token"
```
According to the documentation the plugins order of execution is based on the hooks defind [here](https://buildkite.com/docs/agent/v3/hooks#job-lifecycle-hooks)

Since the plugin cultureamp/aws-assume-role#v0.1.0 hook does not have a definition for environment, the secrets-manager's plugin hooks run before the aws-assume-role plugin's hook. due to which the pipeline job fails since agent underlying role does not access to secrets-manager.

Any suggestions would help.
